### ISSUE TITLE
Jira Attachment File Size

### ISSUE THREAD

**Issue by nitendragautam** [rcarz/jira-client#119]
Hi 
I am trying to attach files in gz format .I could download files without any error ,but go the following error while trying to attach the logs .Logs files are big around 10 mb compressed 
I got the following error while running this client .

Is there any limit in attaching logs ?Please help 

net.rcarz.jiraclient.JiraException: Failed add attachment to issue <xx-xxxx>
	at net.rcarz.jiraclient.Issue.addAttachment(Issue.java:536)
	
Caused by: net.rcarz.jiraclient.RestException: 404 Not Found: The field file exceeds its maximum permitted size of 11564000 bytes.
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:160)
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:194)
	at net.rcarz.jiraclient.RestClient.post(RestClient.java:365)
	at net.rcarz.jiraclient.Issue.addAttachment(Issue.java:534)
	... 2 more

**Comment by Alan-Chen-au** [comment]
check the jira rest api doc : 
https://docs.atlassian.com/jira/REST/latest/#api/2/attachment-getAttachmentMeta

to get the detail about the attachment file size.  
I did not try it before; but hope it is useful for you.

**Comment by Alan-Chen-au** [comment]
the default attachment file size is 10m.  check the doc below. you will get more information . 

https://confluence.atlassian.com/jira061/jira-administrator-s-guide/configuring-global-settings/configuring-file-attachments

**Comment by nitendragautam** [comment]
Thanks for the help .
Yes the default size is 10 MB which caused the error .
We can close this now .

**Comment by Alan-Chen-au** [comment]
no worries!
