### ISSUE TITLE
NullPointerException in Issue.deserialise via JiraClient.searchIssues when using custom field and only returning id,key

### ISSUE THREAD

**Issue by magicdude4eva** [rcarz/jira-client#140]
I created a custom field (TEXT) called ```graylog_md5``` and when doing a search I get a NPE:

```
      Issue.SearchResult srJiraIssues = jira.searchIssues("project = BOB AND Status not in (Closed, Done, Resolved)"
          + " AND (graylog_md5 ~ \"913e12c6ae20566fbdcbe4a175910b44\")",
          "id,key", 1);
```

```
Exception in thread "main" java.lang.NullPointerException
	at net.rcarz.jiraclient.Issue.deserialise(Issue.java:407)
	at net.rcarz.jiraclient.Issue.<init>(Issue.java:395)
	at net.rcarz.jiraclient.Field.getResource(Field.java:311)
	at net.rcarz.jiraclient.Field.getResourceArray(Field.java:393)
	at net.rcarz.jiraclient.Issue.search(Issue.java:908)
	at net.rcarz.jiraclient.Issue.search(Issue.java:836)
	at net.rcarz.jiraclient.JiraClient.searchIssues(JiraClient.java:227)
	at com.bidorbuy.graylog.jira.callback.JiraTest.main(JiraTest.java:32)

```

The NPE is caused due the map returning NULL on the fields:
```
fields = (Map)map.get("fields");
```

As a workaround I have to include ```summary``` in order to have fields populated:
```
      Issue.SearchResult srJiraIssues = jira.searchIssues("project = BOB AND Status not in (Closed, Done, Resolved)"
          + " AND (graylog_md5 ~ \"913e12c6ae20566fbdcbe4a175910b44\")",
          "id,key**,summary**", 1);
```

**Comment by rcarz** [comment]
Thanks, it's fixed in dc5ed2e3f1394742d54d2ad48aaa1cd6082b5c06.
