### ISSUE TITLE
Transition was not found in metadata

### ISSUE THREAD

**Issue by agastyanarumanchi** [rcarz/jira-client#147]
This is the error I get when I try to set assignee or change resolution.Basically when i use transition it doesn't work. Pls help me out.Thanks in advance.This is the code.

public class jiratest {

    public static void main(String[] args) {

        BasicCredentials creds = new BasicCredentials("***", "****");
        JiraClient jira = new JiraClient("https://myportal.reflexisinc.com/JIRA", creds);

        try {
            /* Retrieve issue TEST-123 from JIRA. We'll get an exception if this fails. */
            final Issue issue = jira.getIssue("IM-2");

            /* Print the issue key. */
            System.out.println(issue);

                          
            /* Open the issue and assign it to batman. */
            issue.transition()
                .field(Field.ASSIGNEE, "xyz")
                .execute("Open");

            /* Assign the issue */
            issue.update()
                .field(Field.ASSIGNEE, "xyz")
                .execute();
           } catch (JiraException ex) {
            System.err.println(ex.getMessage());

            if (ex.getCause() != null)
                System.err.println(ex.getCause().getMessage());
        }
    }
}

**Comment by rcarz** [comment]
Perhaps related to #160 

That usually means the state name (Open, in this case) supplied in ```execute``` either doesn't exist or is not available from the current state of the issue.

**Comment by jjwink19** [comment]
I'm seeing the same error but not sure if it's related.  the jira-ext jenkins plugin is invoking a valid state transition "ready-for-test" and it's throwing this:

Run condition [Current build status] enabling prebuild for step [BuilderChain]
Updating JIRA tickets
Operation: Transition tickets
Transition a ticket: ASDT-254
transitionName: ready-for-test
ERROR Updating JIRA, continuing
net.rcarz.jiraclient.JiraException: Transition was not found in metadata
	at net.rcarz.jiraclient.Issue$FluentTransition.getTransition(Issue.java:271)
	at net.rcarz.jiraclient.Issue$FluentTransition.execute(Issue.java:326)
	at org.jenkinsci.plugins.jiraext.svc.impl.JiraClientSvcImpl.changeWorkflowOfTicket(JiraClientSvcImpl.java:108)
	at org.jenkinsci.plugins.jiraext.view.Transition.perform(Transition.java:63)
	at org.jenkinsci.plugins.jiraext.view.JiraExtBuildStep.perform(JiraExtBuildStep.java:61)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finish updating JIRA tickets

I have verified that this is a valid state transition using the DVCS smart commits and "ready-for-test" transitioned the issue.  I'm happy to open up a new issue if more appropriate.  Thanks.  I just saw #160 saying continue discussion here.

**Comment by 2540461056** [comment]
hello sir @rcarz , Im using your cool code and encountered this error too. I copied state from the workflow and paste to the `execute`, but the error exists. The jira version is 1.13, I would like to ask if you have any way to solve it? BTW, Your util is easy to use.

**Comment by 2540461056** [comment]
![image](https://user-images.githubusercontent.com/49741624/194706994-3d8d7f91-3263-4831-941b-01b3262a2685.png)

**Comment by 2540461056** [comment]
![image](https://user-images.githubusercontent.com/49741624/194707031-1b9defea-8e92-4b49-b773-b001c0be5a18.png)

**Comment by 2540461056** [comment]
OK, sir @rcarz , the problem is solved already... BTW, your code is perfect, very cool.
