### ISSUE TITLE
Support for custom field type "option" not complete

### ISSUE THREAD

**Issue by rasei** [rcarz/jira-client#175]
The issue #154 still exists:

Caused by: java.lang.UnsupportedOperationException: option is not a supported field type
at net.rcarz.jiraclient.Field.toJson(Field.java:737)
at net.rcarz.jiraclient.Issue$FluentCreate.executeCreate(Issue.java:102)
at net.rcarz.jiraclient.Issue$FluentCreate.execute(Issue.java:57)

**Comment by jschaeke** [comment]
Hi, any idea when this will be merged and a new release will be set out containing this fix?

**Comment by olada** [comment]
I would also appreciate a merge of this fix. Until then, one will have to fork it and fix himself (or use one of the already fixed forks)
