### ISSUE TITLE
net.rcarz.jiraclient.JiraException: peer not authenticated

### ISSUE THREAD

**Issue by cakushin** [rcarz/jira-client#236]
BasicCredentials creds = new BasicCredentials("***", "****");
JiraClient jira = new JiraClient("https://jira.*****.com", creds);
System.out.println(jira.getProjects());

Exception in thread "main" net.rcarz.jiraclient.JiraException: **peer not authenticated**
	at net.rcarz.jiraclient.JiraClient.getProjects(JiraClient.java:360)
	at com.haogao.util.JiraUtil.main(JiraUtil.java:71)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(Unknown Source)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:126)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:437)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:643)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:126)
	at net.rcarz.jiraclient.RestClient.get(RestClient.java:243)
	at net.rcarz.jiraclient.JiraClient.getProjects(JiraClient.java:349)
	... 1 more

**Comment by v9854268996** [comment]
same issue. Dont know how to fix
