### ISSUE TITLE
Exception in thread "main" net.rcarz.jiraclient.JiraException: Failed to search issues

### ISSUE THREAD

**Issue by arewarabhi** [rcarz/jira-client#277]
Getting below exception when my query giving me result more that 350  count.
Query Ex. - "Project in ("abc") AND component in (abc, pqr) AND status != Resolved AND status != Closed AND status != Fixed ORDER BY created DESC"
above query gives me result more that 350 count.

Exception in thread "main" net.rcarz.jiraclient.JiraException: Failed to search issues
	at net.rcarz.jiraclient.Issue.search(Issue.java:895)
	at net.rcarz.jiraclient.Issue.search(Issue.java:836)
	at net.rcarz.jiraclient.JiraClient.searchIssues(JiraClient.java:227)
	at com.tests.mypackage.JIRAAgeBuckets.JiraProvider(JIRAAgeBuckets.java:31)
	at com.tests.mypackage.JIRAAgeBuckets.setup(JIRAAgeBuckets.java:25)
	at com.tests.mypackage.JIRAAgeBuckets.main(JIRAAgeBuckets.java:235)
Caused by: net.rcarz.jiraclient.RestException: 400 400: {"errorMessages":["Error in the JQL Query: Expecting ')' before the end of the query."],"errors":{}}
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:160)
	at net.rcarz.jiraclient.RestClient.get(RestClient.java:243)
	at net.rcarz.jiraclient.Issue.search(Issue.java:893)
	... 5 more

**Comment by arewarabhi** [comment]
@rcarz could you please check this once

**Comment by arewarabhi** [comment]
I think the issue with the query, so i fix the query and it worked for me. So no action taken as of now on this so closing this ticket.
