### ISSUE TITLE
Exception: Project or issue type missing from create metadata

### ISSUE THREAD

**Issue by blinder** [rcarz/jira-client#41]
Hello! i was trying to just do a simple createIssue() call and received the following exception:

```
net.rcarz.jiraclient.JiraException: Project or issue type missing from create metadata
    at net.rcarz.jiraclient.Issue.getCreateMetadata(Issue.java:467)
    at net.rcarz.jiraclient.Issue.create(Issue.java:661)
    at net.rcarz.jiraclient.JiraClient.createIssue(JiraClient.java:77)
```

My code is very simple, following along with your example:

```
    JiraClient jira = new JiraClient(URL,CREDS);
    Logger.info("Jira client: %s",jira.getSelf());
    Issue issue = jira.createIssue(PROJECT, ISSUE_TYPE)
        .field(Field.SUMMARY, summary)
        .field(Field.DESCRIPTION, description + "\n\nreported by: " + reporter)
        .field(Field.REPORTER, REPORTER)
        .field(Field.LABELS, new String[] {schoolName, reporter})
        .execute();
```

I'm using Jira OnDemand and i have confirmed that 'PROJECT" and 'ISSUE_TYPE' have values. 

I'm not sure if this is a bug in my code, something i'm missing, or an environment problem (given that I'm on OnDemand). 

thanks!

**Comment by rcarz** [comment]
I wasn't able to reproduce this on my instance, and I don't have an On Demand instance to test with. The particular line that causes this exception is checking for expected JSON results from JIRA. The snippet you provided does indeed show issue types are coming back, but I would need to see the full context.

**Comment by alexeyOnGitHub** [comment]
I have the same issue on our in-house JIRA v. 6
