### ISSUE TITLE
net.rcarz.jiraclient.JiraException

### ISSUE THREAD

**Issue by pearlselvan** [rcarz/jira-client#52]
Hi , 

The below is my code for creating the JIRA ticket but its giving the below exception 

public void createIssue() {
		
//		String Jira_PayPal_URL = "https://jira.paypal.com/jira/";
		//https://jira.paypal.com/jira/rest/api/2/issue/createmeta
		String Jira_PayPal_URL ="https://jira.paypal.com/jira/rest/api/2";
	
		BasicCredentials creds = new BasicCredentials("mselvansr", "password");
		JiraClient jira = new JiraClient(Jira_PayPal_URL, creds);
		
		Issue newIssue = null;
		
		try {
			newIssue = jira.createIssue("ECI", "Bug")
			        .field(Field.SUMMARY, "Automation ECI")
			        .field(Field.DESCRIPTION, "Automation On ECI - Demo")
			        .field(Field.REPORTER, "mselvansr")
			        .field(Field.ASSIGNEE, "mselvansr")
			        .execute();
		} catch (JiraException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
            System.out.println(newIssue);
		
		
		
	}

Exception :

null
net.rcarz.jiraclient.JiraException: Failed to retrieve issue metadata
	at net.rcarz.jiraclient.Issue.getCreateMetadata(Issue.java:457)
	at net.rcarz.jiraclient.Issue.create(Issue.java:670)
	at net.rcarz.jiraclient.JiraClient.createIssue(JiraClient.java:77)
	at com.paypal.test.trd.utils.ECIPulse.createIssue(ECIPulse.java:62)
	at com.paypal.test.trd.utils.ECIPulse.main(ECIPulse.java:42)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at com.sun.net.ssl.internal.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:352)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:126)
	at net.rcarz.jiraclient.RestClient.get(RestClient.java:243)
	at net.rcarz.jiraclient.Issue.getCreateMetadata(Issue.java:455)
	... 4 more

**Comment by rcarz** [comment]
Were you able to get it working?

**Comment by rcarz** [comment]
I'm closing this issue since I haven't heard back. Feel free to re-open if you're still having trouble.

**Comment by doubler84** [comment]
I receive the same error, without HTTPS protocol.

**Comment by nallasivam** [comment]
Hi,

I am facing the same issue." javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated".Could you please help me to resolve this.

**Comment by testingxpertshyd** [comment]
Hi @rcarz @pearlselvan 

I'm also getting same issue, Any update on this?

**Comment by totallytot** [comment]
@testingxpertshyd I have not touch this client at all, but as I can see you are trying to use it with Jira Cloud... API token is used there. Also, pls see the following issue: https://github.com/rcarz/jira-client/issues/225

**Comment by testingxpertshyd** [comment]
Hi @rcarz @totallytot ,

Thanks for quick response, I have seen the issue #225 already but i can not get a working solution.
 It would very helpful if you share a working example.

Thanks in advance.

**Comment by testingxpertshyd** [comment]
Hi @rcarz @totallytot @kr-pradeep,

Any update on this?

**Comment by sasipenko** [comment]
> So, i ran into this problem after having it working just fine. And i tried a lot of stuff, before making it work again. Im using the Jenkins jira-ext plugin that uses this code, and i know it sounds strange, but it started to work again, when i added a "/" at the end of the url.
> 
> So, instead of http://jira.192.168.122.214.nip.io
> i changed it to http://jira.192.168.122.214.nip.io/
> 
> And then i worked. I didnt do anything else, so i think this might be the problem. If i remove the trailing /, it stops working again.
> 
> So, maybe that would be a great new commit, to fix this?

We also started running into this today after upgrading various Jenkins plugins. The workaround helped! Thanks

**Comment by Sudharsan93** [comment]
Hello Team,

Is there any update on the above issue. Please let us know the solution to resolve this issue. Thanks.

**Comment by odemeulder-nyt** [comment]
We had a similar issue. Adding the trailing slash to the url worked for us.

**Comment by vzenzo** [comment]
I still have this issue, placing or removing "/" from link does nothing

**Comment by Cocotus** [comment]
> 
> 
> So, i ran into this problem after having it working just fine. And i tried a lot of stuff, before making it work again. Im using the Jenkins jira-ext plugin that uses this code, and i know it sounds strange, but it started to work again, when i added a "/" at the end of the url.
> 
> So, instead of http://jira.192.168.122.214.nip.io
> i changed it to http://jira.192.168.122.214.nip.io/
> 
> And then i worked. I didnt do anything else, so i think this might be the problem. If i remove the trailing /, it stops working again.
> 
> So, maybe that would be a great new commit, to fix this?

Its May 2020 and adding the trailing slash was also the solution here on our Jenkins setup. Incredible find! T H A N K S !

**Comment by lopisronald** [comment]
I still have this issue, placing or removing "/" from link does nothing. 
@rcarz  Could you please help.
