### ISSUE TITLE
SSLPeerUnverifiedException 

### ISSUE THREAD

**Issue by nallasivam** [rcarz/jira-client#89]
Hi, 

I am trying to integrate JIRA. PFB my code.

import net.rcarz.jiraclient.BasicCredentials;
import net.rcarz.jiraclient.Issue;
import net.rcarz.jiraclient.JiraClient;
import net.rcarz.jiraclient.JiraException;

public class Jira {

	public static void main(String[] args) {

	
		BasicCredentials creds = new BasicCredentials(UserName, Pwd);
        JiraClient jira = new JiraClient("URL", creds);
        try {
			Issue issue = jira.getIssue("AWEB-2173");
			 System.out.println(issue);
		} catch (JiraException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}       
	}
}

i am getting the below exception.
net.rcarz.jiraclient.JiraException: Failed to retrieve issue AWEB-2173
	at net.rcarz.jiraclient.Issue.realGet(Issue.java:700)
	at net.rcarz.jiraclient.Issue.get(Issue.java:723)
	at net.rcarz.jiraclient.JiraClient.getIssue(JiraClient.java:90)
	at Jira.main(Jira.java:15)
Caused by: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
	at sun.security.ssl.SSLSessionImpl.getPeerCertificates(SSLSessionImpl.java:431)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:128)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:572)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:640)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:479)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at net.rcarz.jiraclient.RestClient.request(RestClient.java:126)
	at net.rcarz.jiraclient.RestClient.get(RestClient.java:243)
	at net.rcarz.jiraclient.Issue.realGet(Issue.java:698)
	... 3 more

Could you please help me to resolve this

**Comment by SimonSch** [comment]
Hi, I was just going though and saw this question, I know its a few years late but, 

You have to import your .crt certificate into your java cacerts. The easiest way is in firefox. then you will need to open cmd in admin mode and run the following 
`keytool -import -alias example -keystore  "C:\Program Files\Java\jre1.8.0_171\lib\security\cacerts"` 

note you may need to change the jre path. 

Hope it helps.
